ddcz/models/used/creations.py
ddcz/tests/test_integration/test_common_article.py
ddcz/views.py

Redirect properly for mismatching slugs

---

.gitignore
README.md
docker-compose.example.yml
docker-compose.yml

I was thinking that everyone may want to adjust their docker settings and then they would need to think all the time if they are committing the docker-compose.yml or not, so I put that into gitignore and added the example file.

Docker strategy

---

README.md
docs/infrastructure.rst
graveyard/settings/local.example.py

Document production more

---

ddcz/forms/comments.py
ddcz/templates/discussions/phorum-list.html
ddcz/tests/test_integration/test_new_phorum_comment.py
ddcz/views.py
static/common.css

Deleting comments in phorum. Only user of the comment can delete it.
Test has been written for deleting comments. Please check it if it is written well.

Deleting Phorum Comments

---

README.md
ddcz/html.py
ddcz/templates/creative-pages/alchemisttool-list.html
ddcz/templates/creative-pages/commonarticle-list.html
ddcz/templates/creative-pages/html-check-form.html
ddcz/templates/creative-pages/html-check-list.html
ddcz/templates/creative-pages/item-list.html
ddcz/templates/creative-pages/monster-list.html
ddcz/templates/creative-pages/rangerspell-list.html
ddcz/templates/creative-pages/skill-list.html
ddcz/templates/creative-pages/wizardspell-list.html
ddcz/urls.py
ddcz/views.py

HTML checker

---

ddcz/management/commands/deleteauthors.py
ddcz/management/commands/migrateauthors.py
ddcz/management/commands/migratecomments.py
ddcz/management/commands/migratephorum.py

This prevents Heroku from killing the process after 30s.

Report data migration progress

---

ddcz/management/commands/fixit.py

"Vim co s tim je, je to rozbitý!"

Try to fix your local database

---

docker-compose.yml
docs/dictionary.rst

Tavern added to dictionary. 
Fixed port in docker-compose

The Tavern added to dictionary.rst

---

ddcz/management/commands/migrateauthors.py
ddcz/templates/creative-pages/downloaditem-detail.html
ddcz/templatetags/creations.py

After deploy, run `heroku run python manage.py migrateauthors -a dracidoupe`

Random migrations and data fixes

---

ddcz/context_processors.py

It seems that files with ico weren't added, but the code requires them.

Ico back to Svg: Favicon is not in ICO format.

---

ddcz/templatetags/creations.py

Last pull request was missing changes in template tags from gif to svg.

Fix stars in svg

---

Procfile

Migrate on deploy

---

Dockerfile
ddcz/models/used/__init__.py
ddcz/models/used/info.py
ddcz/templates/robots.txt
ddcz/urls.py
ddcz/views.py
graveyard/settings/base.py
graveyard/settings/local.example.py
requirements.txt

Random small tasks from #226 and very basic caching. 
This has a chance of failure thanks to the new memcache setup, so please only mark as approved, I'll deploy myself.

DO NOT MERGE: Random small tasks & Caching

---

ddcz/templates/users/detail.html
ddcz/templates/users/sign_up_after.html
ddcz/views.py
static/common/css/users.css

Added some things from the Sunday call (mix of tasks):
- Sign up: After registration page
- User Profile: Date changed to `czech_date`
- User Profile: `Display: block` on hyperlinks in creations section
I left javascript and style file in new page _sign_up_after.html_ since it will probably be used.

Small changes 

---

ddcz/fixtures/tavernsections.yml
ddcz/models/used/tavern.py
ddcz/tavern.py
ddcz/tests/model_generator.py
ddcz/tests/test_integration/test_tavern/test_access.py
ddcz/tests/test_integration/test_tavern/test_listing.py
ddcz/tests/test_integration/test_tavern_access.py
ddcz/tests/test_integration/test_tavern_listing.py
ddcz/views.py
docs/index.rst
docs/user-docs/index.rst
docs/user-docs/tavern.rst

Future database migrations & model renames (like `id_stolu` actually holding TavernTable reference) delayed as I am waiting for #259

Tests for Tavern & Initial version of updating table access

---

ddcz/views/auth.py

Closes #217
This will change date only if login is called. 
I am thinking we would want to track each time someone is at the web page, but I do not feel the right solution is to set query to a database for each click on the page. Do you know about a better solution? Probably could move this question to #217 if it will be more interesting to discuss.

Tracking last login access

---

ddcz/forms/comments.py
ddcz/forms/tavern.py
ddcz/models/used/tavern.py
ddcz/tavern.py
ddcz/templates/tavern/table-admin.html
ddcz/templates/tavern/table-detail.html
ddcz/templatetags/tavern.py
ddcz/urls.py
ddcz/views/tavern.py
static/common/css/main.css
static/skins/light/css/main.css

* Properly update visit times
* (Un)book
* Cleanup and content to defer some functionalities to #317 
* The important parts of admin form
* Properly increment (unread) post numbers

Further Tavern Dev (refs #210)

---

ddcz/templates/news/newsfeed.html
ddcz/views/news.py
static/common/css/main.css

Show comments in the newsfeed

---

ddcz/models/used/creations.py
ddcz/models/used/discussion.py
ddcz/views/comments.py
ddcz/views/creations.py

Closes #14 
They are now coming as constants from model.
Surprisingly I haven't found more of them, therefore there might still be some of them. I tried find it with IDE but also nothing occurred.

'Magical constants' are gone from views

---

ddcz/templates/creative-pages/alchemisttool-detail.html
ddcz/templates/creative-pages/alchemisttool-list.html
ddcz/templates/creative-pages/commonarticle-detail.html
ddcz/templates/creative-pages/commonarticle-list.html
ddcz/templates/creative-pages/downloaditem-detail.html
ddcz/templates/creative-pages/downloaditem-list.html
ddcz/templates/creative-pages/gallerypicture-detail.html
ddcz/templates/creative-pages/gallerypicture-list.html
ddcz/templates/creative-pages/item-detail.html
ddcz/templates/creative-pages/item-list.html
ddcz/templates/creative-pages/monster-detail.html
ddcz/templates/creative-pages/monster-list.html
ddcz/templates/creative-pages/quest-list.html
ddcz/templates/creative-pages/rangerspell-detail.html
ddcz/templates/creative-pages/rangerspell-list.html
ddcz/templates/creative-pages/skill-detail.html
ddcz/templates/creative-pages/skill-list.html
ddcz/templates/creative-pages/wizardspell-detail.html
ddcz/templates/creative-pages/wizardspell-list.html

Datetime attribute fixed

---

ddcz/templates/dating/list.html
ddcz/templatetags/dating.py

Closes #281 
I am not sure if this template tag is a good solution, but it is a solution for Phase I.
In the future I'd rather do a database table with dating groups and maybe redo the dating page in general, since it is used a lot. But I think for now this is sufficient.

Filter for dating groups

---

ddcz/templates/postal_service/postal_office.html
ddcz/views/postal_service.py

Postal office messages

---

ddcz/forms/authentication.py
requirements.txt

Primarily fix password reset internals

Upgrade to Django 2.2

---

ddcz/forms/signup.py

Age checking method has been raising an exception, since there has been an attemp to concatenate string with integer. Fixed by using f string.
Close #419

fix: Sign up age check
